apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: robomart
  labels:
    project: robomart
    component: frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: robomart
      component: frontend
      tier: frontend
  template:
    metadata:
      labels:
        project: robomart
        component: frontend
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: azharmd/frontend:v1
        imagePullPolicy: Always
        ports:
        - name: liveness-port
          containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: robomart
spec:
  type: LoadBalancer
  selector:
    project: robomart
    component: frontend
    tier: frontend
  ports:
    - protocol: TCP
      port: 80 # service port