apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: robomart
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: robomart
  labels: 
    project: robomart
    component: shipping
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robomart
      component: shipping
      tier: backend
  template:
    metadata:
      labels:
        project: robomart
        component: shipping
        tier: backend
    spec:
      containers:
      - name: shipping
        image: azharmd/shipping:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: robomart
spec:
  selector:
    project: robomart
    component: shipping
    tier: backend
  ports:
  - protocol: TCP 
    port: 8080
    targetPort: 8080
