apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: robomart
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: robomart
  labels: 
    project: robomart
    component: catalogue
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      project: robomart
      component: catalogue
      tier: backend
  template:
    metadata:
      labels:
        project: robomart
        component: catalogue
        tier: backend
    spec:
      containers:
      - name: catalogue
        image: azharmd/catalogue:v1
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: catalogue
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: robomart
spec:
  selector:
    project: robomart
    component: catalogue
    tier: backend
  ports:
  - port: 8080
    targetPort: 8080
