apiVersion: apps/v1
kind: Deployment 
metadata:
  name: redis 
  namespace: robomart
  labels:
    project: robomart
    component: redis
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      project: robomart
      component: redis
      tier: db
  template:
    metadata:
      labels:
        project: robomart
        component: redis
        tier: db
    spec:
      containers:
      - name: redis
        image: azharmd/redis:v1
        imagePullPolicy: Always
        readinessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 40
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: redis 
  namespace: robomart
spec:
  selector:
    project: robomart
    component: redis
    tier: db
  ports:
  - protocol: TCP 
    port: 6379
    targetPort: 6379
